### ISSUE TITLE
conversation not working

### ISSUE THREAD

**Issue by webtaculars** [mvaragnat/botkit-messenger-express-demo#1]
```
debug: GOT A MESSAGE HOOK
{ sender: { id: '1115548341849219' },
  recipient: { id: '944059262358972' },
  timestamp: 1466237246219,
  message:
   { mid: 'mid.1466237246212:73a893daf6ed018644',
     seq: 3608,
     text: 'structured' } }
debug: RECEIVED MESSAGE
debug: CUSTOM FIND CONVO 1115548341849219 1115548341849219
debug: I HEARD [ 'structured' ]
info: [Start]  0  Task for  1115548341849219 in 1115548341849219
debug: CREATED A CONVO FOR 1115548341849219 1115548341849219
info: >   [Start]  0  Conversation with  1115548341849219 in 1115548341849219
debug: No handler for conversationStarted
debug: WEBHOOK SUCCESS {"recipient_id":"1115548341849219","message_id":"mid.1466237247342:164bf9399321b86037"}
debug: WEBHOOK SUCCESS {"recipient_id":"1115548341849219","message_id":"mid.1466237247358:d729042da9662abb97"}

```

conversation get started but then convo.ask does not give any result.

```
controller.hears(['structured'], 'message_received', function(bot, message) {
    bot.startConversation(message, function(err, convo) {

        convo.ask({
            attachment: {
                'type': 'template',
                'payload': {
                    'template_type': 'generic',
                    'elements': [
                        {
                            'title': 'Classic White T-Shirt',
                            'image_url': 'http://petersapparel.parseapp.com/img/item100-thumb.png',
                            'subtitle': 'Soft white cotton t-shirt is back in style',
                            'buttons': [
                                {
                                    'type': 'web_url',
                                    'url': 'https://petersapparel.parseapp.com/view_item?item_id=100',
                                    'title': 'View Item'
                                }
                            ]
                        }
                    ]
                }
            }
        }, function(response, convo) {
            convo.next();
        });
    });
});

```

@mvaragnat

**Comment by webtaculars** [comment]
conversation get started but then convo.ask does not give any result.

**Comment by mvaragnat** [comment]
what do you mean by "does not give any results" ? The structured message is not posted ? The annoying thing with FB Messenger API is that it fails silently. If your attachment is slightly incorrect it would not post anything. Does it post with a normal text message ?

**Comment by webtaculars** [comment]
The structured message will work if I do not use bot.startConversation. Normal text message in bot.startConversation is also not working. Maybe you have not defined a handler for conversation.

**Comment by mvaragnat** [comment]
I'm not sure I understand by "not working". Can you be more specific ? Do you get an error message ? Or the message is not sent ? Or the reply is not heard ?

For example when I do something like below, I am able to have the bot repeat replies.

```
bot.startConversation(message, function(err, convo) {
  var test_message = "How are you?"
  convo.ask(test_message, function(response, convo) {
      convo.say("You said " + response.text)
      convo.next()
   })
})
```

**Comment by webtaculars** [comment]
I copied your the above code in my file. But still it is returning the same result.

> info: [Start]  0  Task for  1115548341849219 in 1115548341849219
> debug: CREATED A CONVO FOR 1115548341849219 1115548341849219
> info: >   [Start]  0  Conversation with  1115548341849219 in 1115548341849219
> debug: No handler for conversationStarted

My dependencies versions are 
`"dependencies": {
    "body-parser": "^1.15.1",
    "botkit": "^0.2.0",
    "dotenv": "^2.0.0",
    "ejs": "^2.4.2",
    "express": "^4.13.4",
    "mongodb": "^1.4.40",
    "mongoose": "^4.5.0",
    "mongoskin": "1.3.20",
    "monkii": "^1.2.0",
    "request": "^2.72.0"
  }
`
Any thing are you able to figure out?

**Comment by mvaragnat** [comment]
That does not mean necessarily a bug. What happens next ? Is the message "How are you?" sent to the conversation ? what happens when you reply ? have you set up a localtunnel webhook url if you're deploying locally ?

**Comment by mvaragnat** [comment]
Closing as it's 2 months old
