### ISSUE TITLE
Conversation does not move on

### ISSUE THREAD

**Issue by natterstefan** [mvaragnat/botkit-messenger-express-demo#11]
Hello,

I implemented the demo and slightly modified it (eg. use `messenger_profile` API). Now I wanted to make the Cookie-Example from Botkit work. It looks like this:

```js
module.exports = function(controller) {

  controller.hears(['cookies'], 'message_received', function(bot, message) {

      bot.startConversation(message, function(err, convo) {

          convo.say('Did someone say cookies!?!!');
          convo.ask('What is your favorite type of cookie?', function(response, convo) {
              convo.say('Golly, I love ' + response.text + ' too!!!');
              convo.next();
          });
      });
  });

};

```

Once I write something like "Give me cookies". I get the "Did someone say cookies!?!!!" response. But then it does not move on to the next `convo.ask`.

I got this in the terminal:

```
TypeError: Cannot read property 'mids' of undefined
    at Object.<anonymous> (/botkit/node_modules/botkit/lib/Facebook.js:19:49)
```

When I comment `controller.trigger('message_delivered', [bot, message])` out from the **botkit.js** file the TypeError is gone but the convo does not move on.

Can anybody help me?

**Comment by natterstefan** [comment]
@mvaragnat Hi, how can I add a PR and propose a solution for this issue?

**Comment by mvaragnat** [comment]
Hey, thanks for being willing to contribute ! But it looks like a fix to Botkit, not this repo, correct?

**Comment by mvaragnat** [comment]
Closing it, I have impression this is stale

**Comment by natterstefan** [comment]
@mvaragnat Ah yeah, sorry I did not reply or updated this issue. I solved it by applying [this fix](https://github.com/howdyai/botkit/issues/503#issuecomment-298318293).
