### ISSUE TITLE
Routing Question

### ISSUE THREAD

**Issue by chriscomrie** [mvaragnat/botkit-messenger-express-demo#4]
You are using routes in this demo like you would use routing if you were serving files on a typical web site. How does the routing work inside messenger? Can you elaborate on what the routes do?

**Comment by mvaragnat** [comment]
Messenger requires only one route, '/webhook', where all messages (or buttons clicks, and so on) information is sent. 

All the dialog logic is then handled by Botkit, through 'controller.hears' functions or events such as 'controller.on('facebook_optin'
