### ISSUE TITLE
debug: No handler for tick

### ISSUE THREAD

**Issue by thierryskoda** [mvaragnat/botkit-messenger-express-demo#5]
I'm continually getting : `debug: No handler for tick` in my logs.

What does this mean?

Thank you!

**Comment by KameronKales** [comment]
just add this to the bottom of your code and it will stop it! In the conversations.js file 
controller.on('tick', function(bot, event) {});

**Comment by KameronKales** [comment]
if you need any more help just shoot me a message! happy to help

**Comment by mvaragnat** [comment]
Good call! You can also pass debug:false to the Botkit instance
