### ISSUE TITLE
Does this support work with the lastest version botkit  and does it support all the facebook api

### ISSUE THREAD

**Issue by aidonsnous** [mvaragnat/botkit-messenger-express-demo#7]
Hello,

I would like to use express.js to build my bot using botkit; the problem is I don't know how to proceed. At first I was thinking to use express I will just have to install it in my botkit project and use it as normal node.js app and that's all; but with what the first issue is describing as problem, it sounds like to have botkit project work with express there a lot to configure and also features problem.

Help me understand how I can use express with botkit.

**Comment by mvaragnat** [comment]
This project is indeed a demo of how to integrate Botkit within an Express app, instead of using Botkit's router. Check out the code :-)
