### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by deepakmhr** [mvaragnat/botkit-messenger-express-demo#8]
// this function processes the POST request to the webhook
var handler = function(obj) {
    controller.debug('Message received from FB')
    var message
    if (obj.entry) {
        for (var e = 0; e < obj.entry.length; e++) {
            for (var m = 0; m < obj.entry[e].messaging.length; m++) {
                var facebook_message = obj.entry[e].messaging[m]
                    // /console.log(facebook_message)
                    // normal message
                if (facebook_message.message) {
                    message = {
                        text: facebook_message.message.text,
                        user: facebook_message.sender.id,
                        channel: facebook_message.sender.id,
                        timestamp: facebook_message.timestamp,
                        seq: facebook_message.message.seq,
                        mid: facebook_message.message.mid,
                        attachments: facebook_message.message.attachments
                    }
....
...

I don't know why length is coming zero at **obj.entry[e].messaging.length;**

I am regularly getting this error message while receiving request from Facebook
'
Is there an issue with custom code or botkit framework ?

**Comment by mvaragnat** [comment]
Most likely with custom code :-) I suppose Facebook has added messages type with a different format. Can you print to logs the message received?

**Comment by mvaragnat** [comment]
Closing it, I'm under impression that this is stale
